title: Anurudh Peduri

theme: jekyll-theme-primer
markdown: kramdown
kramdown:
  math_engine: mathjax
  # parse markdown inside HTML tags
  parse_block_html: true

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"
      excerpt_separator: "<!--more-->"

exclude:
  - .vs
  - vendor
  - scripts
  - Makefile
  - README.md
  - TODOS.md
  - blogs/**/*.lhs
