name: anurudhp.github.io
title: null

theme: jekyll-theme-primer
markdown: kramdown
kramdown:
  math_engine: mathjax

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"

exclude: ["README.md", "scripts", "Makefile"]
